USE deview;

-- 기술면접데이터 로드
LOAD DATA INFILE '/var/lib/mysql-files/기술면접컨텐츠데이터-종합.csv'
INTO TABLE TECH_INTERVIEW
CHARACTER SET utf8mb4  -- 한글 깨짐 방지
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS  -- (첫 번째 줄(헤더) 무시)
(TECH_INTERVIEW_ID, HGH_QST_NUM, CATEGORY, KEYWORD, QUESTION, ANSWER, HGH_QST_YN);


-- 학습컨텐츠데이터 로드
LOAD DATA INFILE '/var/lib/mysql-files/학습컨텐츠데이터-종합.csv'
INTO TABLE STUDY_CONTENT
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS
(STUDY_CONTENT_ID, FIRST_CATEGORY, SECOND_CATEGORY, TITLE, BODY);